defaults:
    - task: semseg
    - model: ssg
    - task_model: ${defaults.0.task}-${defaults.1.model}
    - dataset: psnet

hydra:
  run:
    dir: outputs-psnet

gpus:
    - 0

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
